### ISSUE TITLE
Enabling SSL/HTTPS on a different port

### ISSUE THREAD

**Issue by radrad** [jorgeclaro/thingworx-docker#4]
I cannot find a way to enable/edit docker installation to add HTTPS protocol and port number.
I would like to add self-signed certificate like on Thingworx standalone installation like explained here:
 https://support.ptc.com/appserver/cs/view/solution.jsp?n=CS193947&lang=en_US.

How to do equivalent thing in Docker installation?
Thanks,
Rad

**Comment by jorgeclaro** [comment]
This image is not targeted for production environment. The exposed port can be changed when launching the container, but if you need to configure some more specific options like HTTPS or the internal port, you can always follow the original documentation from PTC.
